// Export public API for account-management module
export { AdminAccountManagementPage } from './view/pages/AdminAccountManagementPage'
export { AddAdminPage } from './view/pages/CreateAdminPage'
export { AdminDetailPage } from './view/pages/AdminDetailPage'
export { EditAdminPage } from './view/pages/EditAdminPage'
export { InstructorAccountManagementPage } from './view/pages/InstructorAccountManagementPage'
export { AddInstructorPage } from './view/pages/CreateInstructorPage'
export { InstructorDetailPage } from './view/pages/InstructorDetailPage'
export { EditInstructorPage } from './view/pages/EditInstructorPage'
export { TeacherAccountManagementPage } from './view/pages/TeacherAccountManagementPage'
export { AddTeacherPage } from './view/pages/CreateTeacherPage'
export { TeacherDetailPage } from './view/pages/TeacherDetailPage'
export { EditTeacherPage } from './view/pages/EditTeacherPage'
export { AdminAccountSettingsPage } from './view/pages/AdminAccountSettingsPage'
export { ProfileSettingsAdminPage } from './view/pages/ProfileSettingsAdminPage'
export { ProfileSettingsInstructorPage } from './view/pages/ProfileSettingsInstructorPage'
export { ProfileSettingsTeacherPage } from './view/pages/ProfileSettingsTeacherPage'
export { useAdminAccountsQuery, useAdminDetailQuery, useInstructorAccountsQuery, useInstructorDetailQuery, useTeacherAccountsQuery, useTeacherDetailQuery } from './controller/queries'
export type { AdminAccount, AdminDetail, InstructorAccount, InstructorDetail, TeacherAccount, TeacherDetail } from './model/account-management.types'