export const ROUTES = {
  // Admin routes - path segments only
  ADMIN: '/admin',
  ADMIN_DASHBOARD: 'dashboard',
  ADMIN_PROGRAM_MANAGEMENT: 'program',
  ADMIN_PROGRAM: 'program',
  ADMIN_PROGRAM_CREATE: 'create',
  ADMIN_PROGRAM_EDIT: ':id/edit',
  ADMIN_MASTER_CODE_SETUP: 'master-code-setup',
  ADMIN_MASTER_CODE_SETUP_CREATE: 'create',
  ADMIN_COMMON_CODE: 'common-code',
  ADMIN_INSTITUTION: 'institution',
  ADMIN_INSTITUTION_CREATE: 'create',
  ADMIN_INSTITUTION_EDIT: ':id/edit',
  ADMIN_ACCOUNT_MANAGEMENT: 'account-management',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS: 'admins',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_CREATE: 'create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS: 'instructors',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_CREATE: 'create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_DETAIL: ':id',
  ADMIN_TRAINING: 'training',
  ADMIN_TRAINING_CREATE: 'create',
  // Instructor routes - path segments only
  INSTRUCTOR: '/instructor',
  INSTRUCTOR_DASHBOARD: 'dashboard',
  // Full paths for navigation (computed from segments)
  ADMIN_DASHBOARD_FULL: '/admin/dashboard',
  ADMIN_PROGRAM_MANAGEMENT_FULL: '/admin/program',
  ADMIN_PROGRAM_FULL: '/admin/program',
  ADMIN_PROGRAM_CREATE_FULL: '/admin/program/create',
  ADMIN_PROGRAM_EDIT_FULL: '/admin/program/:id/edit',
  ADMIN_MASTER_CODE_SETUP_FULL: '/admin/master-code-setup',
  ADMIN_MASTER_CODE_SETUP_CREATE_FULL: '/admin/master-code-setup/create',
  ADMIN_COMMON_CODE_FULL: '/admin/common-code',
  ADMIN_INSTITUTION_FULL: '/admin/institution',
  ADMIN_INSTITUTION_CREATE_FULL: '/admin/institution/create',
  ADMIN_INSTITUTION_EDIT_FULL: '/admin/institution/:id/edit',
  ADMIN_ACCOUNT_MANAGEMENT_FULL: '/admin/account-management',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_FULL: '/admin/account-management/admins',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_CREATE_FULL: '/admin/account-management/admins/create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_FULL: '/admin/account-management/instructors',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_CREATE_FULL: '/admin/account-management/instructors/create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_DETAIL_FULL: '/admin/account-management/instructors/:id',
  ADMIN_TRAINING_FULL: '/admin/training',
  ADMIN_TRAINING_CREATE_FULL: '/admin/training/create',
  INSTRUCTOR_DASHBOARD_FULL: '/instructor/dashboard',
  // Auth
  LOGIN: '/login',
  NOT_FOUND: '/404',
  UNAUTHORIZED: '/403',
} as const

