export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  // Admin routes - path segments only
  ADMIN: '/admin',
  ADMIN_DASHBOARD: 'dashboard',
  ADMIN_EDUCATION_OPERATIONS: 'education-operations',
  ADMIN_INSTRUCTOR_ASSIGNMENT: 'instructor-assignment',
  ADMIN_INSTRUCTOR_APPLICATION_MANAGEMENT: 'application',
  ADMIN_INSTRUCTOR_ALLOCATION_MANAGEMENT: 'allocation',
  ADMIN_TEACHING_CONFIRMATION_MANAGEMENT: 'confirmation',
  ADMIN_REFERENCE_INFORMATION_MANAGEMENT: 'reference-information-management',
  ADMIN_INSTITUTION_MANAGEMENT: 'institution',
  ADMIN_PROGRAM_MANAGEMENT: 'program',
  ADMIN_INSTRUCTOR_MANAGEMENT: 'instructor',
  ADMIN_SYSTEM_MANAGEMENT: 'system-management',
  ADMIN_SETTINGS_AND_USER_MANAGEMENT: 'settings',
  ADMIN_ACCOUNT_MANAGEMENT: 'account-management',
  // Instructor routes - path segments only
  INSTRUCTOR: '/instructor',
  INSTRUCTOR_DASHBOARD: 'dashboard',
  INSTRUCTOR_EDUCATION_OPERATIONS: 'education-operations',
  INSTRUCTOR_SCHEDULE: 'instructor-assignment',
  INSTRUCTOR_STUDENTS: 'reference-information-management',
  INSTRUCTOR_ATTENDANCE: 'system-management',
  INSTRUCTOR_GRADES: 'settings',
  // Full paths for navigation (computed from segments)
  ADMIN_DASHBOARD_FULL: '/admin/dashboard',
  ADMIN_EDUCATION_OPERATIONS_FULL: '/admin/education-operations',
  ADMIN_INSTRUCTOR_ASSIGNMENT_FULL: '/admin/instructor-assignment',
  ADMIN_INSTRUCTOR_APPLICATION_MANAGEMENT_FULL: '/admin/instructor-assignment/application',
  ADMIN_INSTRUCTOR_ALLOCATION_MANAGEMENT_FULL: '/admin/instructor-assignment/allocation',
  ADMIN_TEACHING_CONFIRMATION_MANAGEMENT_FULL: '/admin/instructor-assignment/confirmation',
  ADMIN_REFERENCE_INFORMATION_MANAGEMENT_FULL: '/admin/reference-information-management',
  ADMIN_INSTITUTION_MANAGEMENT_FULL: '/admin/reference-information-management/institution',
  ADMIN_PROGRAM_MANAGEMENT_FULL: '/admin/reference-information-management/program',
  ADMIN_INSTRUCTOR_MANAGEMENT_FULL: '/admin/reference-information-management/instructor',
  ADMIN_SYSTEM_MANAGEMENT_FULL: '/admin/system-management',
  ADMIN_SETTINGS_AND_USER_MANAGEMENT_FULL: '/admin/system-management/settings',
  ADMIN_ACCOUNT_MANAGEMENT_FULL: '/admin/account-management',
  INSTRUCTOR_DASHBOARD_FULL: '/instructor/dashboard',
  INSTRUCTOR_EDUCATION_OPERATIONS_FULL: '/instructor/education-operations',
  INSTRUCTOR_SCHEDULE_FULL: '/instructor/instructor-assignment',
  INSTRUCTOR_STUDENTS_FULL: '/instructor/reference-information-management',
  INSTRUCTOR_ATTENDANCE_FULL: '/instructor/system-management',
  INSTRUCTOR_GRADES_FULL: '/instructor/system-management/settings',
  // Legacy routes (for backward compatibility)
  // Education Operations
  EDUCATION_OPERATIONS: '/education-operations',
  // Instructor Assignment
  INSTRUCTOR_ASSIGNMENT: '/instructor-assignment',
  INSTRUCTOR_APPLICATION_MANAGEMENT: '/instructor-assignment/application',
  INSTRUCTOR_ALLOCATION_MANAGEMENT: '/instructor-assignment/allocation',
  TEACHING_CONFIRMATION_MANAGEMENT: '/instructor-assignment/confirmation',
  // Reference Information Management
  REFERENCE_INFORMATION_MANAGEMENT: '/reference-information-management',
  INSTITUTION_MANAGEMENT: '/reference-information-management/institution',
  PROGRAM_MANAGEMENT: '/reference-information-management/program',
  INSTRUCTOR_MANAGEMENT: '/reference-information-management/instructor',
  // System Management
  SYSTEM_MANAGEMENT: '/system-management',
  SETTINGS_AND_USER_MANAGEMENT: '/system-management/settings',
  // Auth
  LOGIN: '/login',
  NOT_FOUND: '/404',
  UNAUTHORIZED: '/403',
} as const

