export const ROUTES = {
  // Admin routes - path segments only
  ADMIN: '/admin',
  ADMIN_DASHBOARD: 'dashboard',
  ADMIN_PROGRAM_MANAGEMENT: 'program',
  ADMIN_PROGRAM: 'program',
  ADMIN_PROGRAM_CREATE: 'create',
  ADMIN_PROGRAM_EDIT: ':id/edit',
  ADMIN_MASTER_CODE_SETUP: 'master-code-setup',
  ADMIN_MASTER_CODE_SETUP_CREATE: 'create',
  ADMIN_COMMON_CODE: 'common-code',
  ADMIN_INSTITUTION: 'institution',
  ADMIN_INSTITUTION_CREATE: 'create',
  ADMIN_INSTITUTION_EDIT: ':id/edit',
  ADMIN_ACCOUNT_MANAGEMENT: 'account-management',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS: 'admins',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_CREATE: 'create',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_DETAIL: ':username',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_EDIT: ':username/edit',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS: 'instructors',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_CREATE: 'create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_DETAIL: ':id',
  ADMIN_TRAINING: 'training',
  ADMIN_TRAINING_CREATE: 'create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_EDIT: ':id/edit',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS: 'teachers',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS_CREATE: 'create',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS_DETAIL: ':id',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS_EDIT: ':id/edit',
  // Instructor routes - path segments only
  INSTRUCTOR: '/instructor',
  INSTRUCTOR_DASHBOARD: 'dashboard',
  // Teacher routes - path segments only
  TEACHER: '/teacher',
  TEACHER_DASHBOARD: 'dashboard',
  // Account settings routes (for all account types)
  ACCOUNT_SETTINGS: 'account-settings',
  PROFILE_SETTINGS: 'profile-settings',
  // Full paths for navigation (computed from segments)
  ADMIN_DASHBOARD_FULL: '/admin/dashboard',
  ADMIN_PROGRAM_MANAGEMENT_FULL: '/admin/program',
  ADMIN_PROGRAM_FULL: '/admin/program',
  ADMIN_PROGRAM_CREATE_FULL: '/admin/program/create',
  ADMIN_PROGRAM_EDIT_FULL: '/admin/program/:id/edit',
  ADMIN_MASTER_CODE_SETUP_FULL: '/admin/master-code-setup',
  ADMIN_MASTER_CODE_SETUP_CREATE_FULL: '/admin/master-code-setup/create',
  ADMIN_COMMON_CODE_FULL: '/admin/common-code',
  ADMIN_INSTITUTION_FULL: '/admin/institution',
  ADMIN_INSTITUTION_CREATE_FULL: '/admin/institution/create',
  ADMIN_INSTITUTION_EDIT_FULL: '/admin/institution/:id/edit',
  ADMIN_ACCOUNT_MANAGEMENT_FULL: '/admin/account-management',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_FULL: '/admin/account-management/admins',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_CREATE_FULL: '/admin/account-management/admins/create',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_DETAIL_FULL: '/admin/account-management/admins/:username',
  ADMIN_ACCOUNT_MANAGEMENT_ADMINS_EDIT_FULL: '/admin/account-management/admins/:username/edit',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_FULL: '/admin/account-management/instructors',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_CREATE_FULL: '/admin/account-management/instructors/create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_DETAIL_FULL: '/admin/account-management/instructors/:id',
  ADMIN_TRAINING_FULL: '/admin/training',
  ADMIN_TRAINING_CREATE_FULL: '/admin/training/create',
  ADMIN_ACCOUNT_MANAGEMENT_INSTRUCTORS_EDIT_FULL: '/admin/account-management/instructors/:id/edit',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS_FULL: '/admin/account-management/teachers',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS_CREATE_FULL: '/admin/account-management/teachers/create',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS_DETAIL_FULL: '/admin/account-management/teachers/:id',
  ADMIN_ACCOUNT_MANAGEMENT_TEACHERS_EDIT_FULL: '/admin/account-management/teachers/:id/edit',
  INSTRUCTOR_DASHBOARD_FULL: '/instructor/dashboard',
  TEACHER_DASHBOARD_FULL: '/teacher/dashboard',
  // Account settings full paths
  ADMIN_ACCOUNT_SETTINGS_FULL: '/admin/account-settings',
  ADMIN_PROFILE_SETTINGS_FULL: '/admin/profile-settings',
  ADMIN_TEACHER_PROFILE_SETTINGS_FULL: '/admin/teacher-profile-settings',
  INSTRUCTOR_ACCOUNT_SETTINGS_FULL: '/instructor/account-settings',
  INSTRUCTOR_PROFILE_SETTINGS_FULL: '/instructor/profile-settings',
  TEACHER_ACCOUNT_SETTINGS_FULL: '/teacher/account-settings',
  TEACHER_PROFILE_SETTINGS_FULL: '/teacher/profile-settings',
  // Auth
  LOGIN: '/login',
  NOT_FOUND: '/404',
  UNAUTHORIZED: '/403',

  HOME: '/',
} as const

